#!/bin/bash

if [[ $(whoami) != "root" ]]
then
	echo "Ups, skrip ini harus dieksekusi dengan modus root."
	exit
fi

BASE_TEMP_MOUNTPOINT="/tmp/buat-livecd_$DATE"
TEMP_ISO_MOUNTPOINT=""
TEMP_LOS_MOUNTPOINT=""
TEMP_RFS_MOUNTPOINT=""
if [ -f "/usr/lib/ign-buat-livecd/common.sh" ]; then
	. "/usr/lib/ign-buat-livecd/common.sh"
elif [ -f "./lib/common.sh" ]; then
	. "./lib/common.sh"
fi

if [[ "$IGN_LIB_LOADED" != "true" ]]; then
	echo "Berkas common.sh tidak ditemukan!"
	exit 1
fi

function s_check_conf {
	ERR=0

	# Container
	if [[ "$CONTAINER_SIZE" -lt "3" ]]; then
		e_log "Ukuran container terlalu kecil!"
		ERR=1
	fi

	# IGN root directory
	if [ ! -d "$IGN_DIR" ]; then
		e_log "Direktori root IGN tidak ditemukan!"
		ERR=1
	fi

	# Working directory
	if [ ! -d "$WORKING_DIR" ]; then
		e_log "Direktori output tidak ditemukan!"
		ERR=1
	fi

	# Interactive shell
	if [[ "$INTERACTIVE_SHELL" != "" && "$INTERACTIVE_SHELL" != "0" && "$INTERACTIVE_SHELL" != "1" ]]; then
		e_log "Mode interactive shell tidak dikenali!"
		ERR=1
	fi

	# SquashFS compression method
	if [[ "$SQUASHFS_COMP" != "" && "$SQUASHFS_COMP" != "gzip" && "$SQUASHFS_COMP" != "xz" ]]; then
		e_log "Metode kompresi SquashFS tidak dikenali!"
		ERR=1
	fi

	# Generate MD5
	if [[ "$GENERATE_MD5" != "" && "$GENERATE_MD5" != "0" && "$GENERATE_MD5" != "1" ]]; then
		e_log "Opsi pembuatan MD5 sum tidak dikenali!"
		ERR=1
	fi

	if [[ "$ERR" == "1" ]]; then
		exit 1
	fi
}

function s_check_isoconf {
	ERR=0
	FILES_TO_CHECK="iso/isolinux/boot.cat iso/isolinux/isolinux.bin iso/isolinux/isolinux.cfg buat-livecd.ks"
	for a in $FILES_TO_CHECK; do
		if [ ! -f "$ISO_CONF/$a" ]; then
			e_log "Berkas $ISO_CONF/$a tidak ditemukan!"
			ERR=1
		fi
	done

	if [[ "$ERR" == "1" ]]; then
		exit 1
	fi
}

function s_chroot_root {
	systemd-nspawn -q -D "$IGN_DIR" "$@"
}

function s_chroot_cont {
	systemd-nspawn -q -D "$TEMP_DIR/container" "$@"
}

function s_mount_cont {
	if [ ! -d "$TEMP_DIR/container" ]; then
		mkdir "$TEMP_DIR/container"
	fi
	mount "$TEMP_DIR/LiveOS/rootfs.img" "$TEMP_DIR/container"
}

function s_umount_cont {
	sync
	umount -l "$TEMP_DIR/container"
}

function s_help {
	echo "Penggunaan: ign-buat-livecd [opsi]"
	echo "Buat LiveCD IGOS Nusantara"
	echo ""
	echo "Opsi:"
	echo "  -c, --config <direktori>   Direktori konfigurasi LiveCD"
	echo "                             (default: /usr/share/buat-livecd/)"
	echo "  -f, --fast                 Gunakan mode cepat, berguna saat pengujian"
	echo "                             (kompresi GZip, tidak membuat MD5 sum, dll)"
	echo "  -m, --modify               Masuk ke modus interaktif untuk memodifikasi LiveOS"
	echo "  -o, --output <direktori>   Direktori output"
	echo "                             (default: $HOME)"
	echo "  -r, --root <direktori>     Direktori root IGOS Nusantara"
	echo "                             (default: /)"
	echo "  -i, --from-iso <iso>       Gunakan berkas ISO IGOS Nusantara sebagai sumber"
	echo "                             (akan otomatis mengatur direktori root)"
	echo "  -s, --size <ukuran>        Ukuran kontainer LiveOS (dalam satuan GiB)"
	echo "                             (default: 10)"
	echo "  -h, --help                 Tampilkan bantuan ini"
	echo "  -v, --version              Tampilkan versi skrip ini"
}

CMDLINE=$(getopt -o c:fhmo:r:i:s:v --long config:,fast,help,modify,output:,from-iso:,root:,size:,version -n "ign-buat-livecd" -- "$@")
eval set -- "$CMDLINE"

while true; do
	case "$1" in
		-c | --config )
			if [ -d "$2" ]; then
				ISO_CONF="$(readlink -f $2)"
			else
				e_log "Oops, direktori konfigurasi \'$2\' tidak ada :("
				exit 1
			fi
			shift 2
			;;
		-f | --fast )
			FAST_="1"
			shift
			;;
		-h | --help )
			s_help
			exit
			;;
		-m | --modify )
			INTERACTIVE_SHELL_="1"
			shift
			;;
		-o | --output )
			if [ -d "$2" ]; then
				WORKING_DIR_="$(readlink -f $2)"
			else
				e_log "Direktori output \'$2\' tidak ditemukan!"
				exit 1
			fi
			shift 2
			;;
		-r | --root )
			if [ -d "$2" ]; then
				IGN_DIR_="$(readlink -f $2)"
			else
				e_log "Direktori root IGN \'$2\' tidak ditemukan!"
				exit 1
			fi
			shift 2
			;;
		-i | --from-iso )
			if [ -e "$2" ]; then
				SOURCE_ISO="$(readlink -f $2)"
			else
				e_log "Berkas ISO IGN \'$2\' tidak ditemukan!"
				exit 1
			fi
			shift 2
			;;
		-s | --size )
			CONTAINER_SIZE_="$2"
			shift 2
			;;
		-v | --version )
			echo "Buat LiveCD IGOS Nusantara versi $VERSION"
			echo "Dibuat oleh $CREDIT"
			echo "Didistribusikan dengan lisensi MIT"
			exit
			;;
		-- )
			shift
			break
			;;
		* )
			break
			;;
	esac
done

# Check for dependencies
DEPS="mount md5sum mkfs.ext4 mksquashfs rsync systemd-nspawn xorriso"
if [[ "$SOURCE_ISO" != "" ]]; then
	DEPS="$DEPS fuseiso fusermount"
fi

for a in $DEPS; do
	if [[ "$(which $a)" == "" ]]; then
		e_log "Perintah \'$a\' tidak ditemukan!"
		DEPS_ERR=1
	fi
done
if [[ "$DEPS_ERR" == "1" ]]; then exit 1; fi
# END: Check for dependencies

# Configuration
CONTAINER_UUID="16051605-1605-1605-1605-160516051605"

if [[ "$ISO_CONF" == "" ]]; then
	ISO_CONF="/usr/share/buat-livecd/"
fi

if [ -f "$ISO_CONF/config.cfg" ]; then
	. "$ISO_CONF/config.cfg"
fi

if [[ "$HOSTNAME" == "" ]]; then
	HOSTNAME="nusantara"
fi

if [[ "$LIVE_USER" == "" ]]; then
	LIVE_USER="liveuser"
fi

if [[ "$LIVE_USER_FULLNAME" == "" ]]; then
	LIVE_USER="Live User"
fi

if [[ "$LOCAL_USER" == "" ]]; then
	LIVE_USER="igos"
fi

if [[ "$LOCAL_USER_FULLNAME" == "" ]]; then
	LIVE_USER="IGOS Nusantara"
fi

if [[ "$CONTAINER_SIZE" == "" ]]; then
	CONTAINER_SIZE="10"
fi

if [[ "$IGN_DIR" == "" ]]; then
	IGN_DIR="/"
fi

if [[ "$WORKING_DIR" == "" ]]; then
	WORKING_DIR="$HOME"
fi

if [[ "$INTERACTIVE_SHELL" == "" ]]; then
	INTERACTIVE_SHELL="0"
fi

if [[ "$SQUASHFS_COMP" == "" ]]; then
	SQUASHFS_COMP="xz"
fi

if [[ "$GENERATE_MD5" == "" ]]; then
	GENERATE_MD5="1"
fi

# Override config.cfg values
if [[ "$FAST_" = "1" ]]; then
	SQUASHFS_COMP="gzip"
	GENERATE_MD5="0"
fi

if [[ "$INTERACTIVE_SHELL_" = "1" ]]; then
	INTERACTIVE_SHELL="1"
fi

if [[ "$WORKING_DIR_" != "" ]]; then
	WORKING_DIR="$WORKING_DIR_"
fi

if [[ "$CONTAINER_SIZE_" != "" ]]; then
	CONTAINER_SIZE="$CONTAINER_SIZE_"
fi

if [[ "$IGN_DIR_" != "" ]]; then
	IGN_DIR="$IGN_DIR_"
fi

# Load IGN from source ISO
if [[ "$SOURCE_ISO" != "" ]]; then
	s_log "Mengaitkan berkas sumber..."
	s_mount_iso
	IGN_DIR="$BASE_TEMP_MOUNTPOINT/rootfs"
	echo ""
fi

TEMP_DIR="$WORKING_DIR/buat-livecd"
# END: Configuration

s_check_conf
s_check_isoconf

s_log "============================"
s_log " Buat LiveCD IGOS Nusantara "
s_log "============================"

s_log ""
s_log "-> Konfigurasi        $ISO_CONF"
s_log "-> Hostname           $HOSTNAME"
s_log "-> Pengguna live      $LIVE_USER ($LIVE_USER_FULLNAME)"
s_log "-> Pengguna lokal     $LOCAL_USER ($LOCAL_USER_FULLNAME)"
s_log "-> Pengguna dihapus   $USERS_TO_DEL"
s_log "-> Ukuran container   $CONTAINER_SIZE GiB"
s_log "-> Kompresi           $SQUASHFS_COMP"
s_log "-> Modus interaktif?  $INTERACTIVE_SHELL"
s_log "-> Buat MD5 sum?      $GENERATE_MD5"
s_log "-> Direktori IGN      $IGN_DIR"
s_log "-> Direktori output   $WORKING_DIR"
s_log "-> Dir. sementara     $TEMP_DIR"
s_log ""

read -p "Tekan [Enter] untuk melanjutkan, Ctrl-C untuk membatalkan..."
echo ""

mkdir -p "$TEMP_DIR/LiveOS/"

# Create sparse file and format it
s_log "Membuat filesystem..."
s_log "-> Membuat container ($CONTAINER_SIZE GiB)..."
SYSSIZE=$(echo "($CONTAINER_SIZE * 1024 * 1024 * 1024)" | bc)
dd if=/dev/null of=$TEMP_DIR/LiveOS/rootfs.img seek=$SYSSIZE bs=1 > /dev/null
s_log "-> Memformat container..."
mkfs.ext4 -L "_IGNX" -U "$CONTAINER_UUID" "$TEMP_DIR/LiveOS/rootfs.img" > /dev/null

s_log "Menyalin sistem ke container..."
s_log "-> Mengaitkan container..."
s_mount_cont

# Copy system files
s_log "-> Menyalin sistem..."
s_log "   (prosesnya cukup lama, tergantung ukuran sistem)"
rsync -avPHpEAXogS --specials --quiet \
	--exclude="dev/*" --exclude="proc/*" \
	--exclude="sys/*" --exclude="run/*" \
	--exclude="media/*" --exclude="mnt/*" \
	--exclude="home/*" --exclude="root/*" \
	--exclude="tmp/*" --exclude="var/backups/*" \
	--exclude="var/cache/*" --exclude="var/run/*" \
	--exclude="var/log/*" --exclude="var/mail/*" \
	--exclude="var/spool/*" --exclude="var/tmp/*" \
	$IGN_DIR/ $TEMP_DIR/container

# Delete users
if [[ "$USERS_TO_DEL" != "" ]]; then
	s_log "-> Menghapus pengguna..."
	for a in $USERS_TO_DEL; do
		s_chroot_cont userdel -r $a
	done
fi

# Create default users
s_log "-> Membuat pengguna live dan local..."
s_chroot_cont useradd -c "$LIVE_USER_FULLNAME" -m -U $LIVE_USER
if [ ! -d "$TEMP_DIR/container/etc/buat-livecd" ]; then
	mkdir "$TEMP_DIR/container/etc/buat-livecd"
fi
cat "$ISO_CONF/buat-livecd.ks" | sed -e "s/___LIVEUSER___/$LIVE_USER/" \
	-e "s/___LOCALUSER___/$LOCAL_USER/" \
	-e "s/___LOCALUSERFULLNAME___/$LOCAL_USER_FULLNAME/" \
	> "$TEMP_DIR/container/etc/buat-livecd/buat-livecd.ks"

# Set default configuration
s_log "-> Mengatur konfigurasi default..."

## Set /etc/fstab
echo "UUID=$CONTAINER_UUID / ext4 defaults 0 0" > "$TEMP_DIR/container/etc/fstab"

## Create desktop shortcut
cat <<EOF > $TEMP_DIR/container/usr/share/applications/liveinst.desktop
[Desktop Entry]
Name=Install to Hard Drive
Name[en@quot]=Install to Hard Drive
Name[id]=Pasang ke Harddisk
GenericName=Install
GenericName[en@quot]=Install
GenericName[en_GB]=Install
GenericName[id]=Pasang
Categories=System;Utility;X-Red-Hat-Base;X-Fedora;GNOME;GTK;
Exec=/usr/bin/liveinst --kickstart /etc/buat-livecd/buat-livecd.ks
Terminal=false
Type=Application
Icon=anaconda
Encoding=UTF-8
StartupNotify=false
NoDisplay=true
X-Desktop-File-Install-Version=0.19
EOF

## Reset password
s_log "   Mengatur ulang sandi pengguna..."
s_chroot_cont passwd -d root
s_chroot_cont passwd -d $LIVE_USER

## Set hostname
s_log "   Mengatur hostname..."
echo "$HOSTNAME" > "$TEMP_DIR/container/etc/hostname"

## Set /etc/hosts
s_log "   Mengatur hosts..."
echo -e "127.0.0.1\tlocalhost" > "$TEMP_DIR/container/etc/hosts"
echo -e "127.0.0.1\t$HOSTNAME" >> "$TEMP_DIR/container/etc/hosts"

# Clean things up
s_log "-> Bersih-bersih sistem..."
## DNF's cache
if [[ $(s_chroot_cont which dnf) != "" ]]; then
	DNF_FOUND="1"
	s_log "   Membersihkan data DNF..."
	s_chroot_cont dnf clean all
fi
## YUM's cache
if [[ $(s_chroot_cont which yum) != "" && "$DNF_FOUND" != "1" ]]; then
	s_log "   Membersihkan data YUM..."
	s_chroot_cont yum clean all
fi

# Interactive shell
if [[ "$INTERACTIVE_SHELL" == "1" ]]; then
	s_log "-> Masuk ke modus interaktif..."
	s_log "   ('exit' untuk keluar dari modus interaktif)"
	s_log "   Container ada di $TEMP_DIR/container"
	s_log ""
	s_chroot_cont
fi

# Unmount rootfs.img
s_log "-> Melepas kait container..."
s_umount_cont

# Do filesystem check
s_log "-> Memeriksa container..."
fsck -y "$TEMP_DIR/LiveOS/rootfs.img" > /dev/null

# Create ISO
s_log ""
s_log "Membuat ISO..."
mkdir "$TEMP_DIR/temp_iso"

## Copy templates
s_log "-> Menyalin konfigurasi ISO..."
rsync -avP --quiet "$ISO_CONF/iso/" "$TEMP_DIR/temp_iso/"

## Kernel and ramdisk
s_log "-> Menyalin kernel dan ramdisk..."

### Find latest kernel
KERNEL_VER=$(find $IGN_DIR/boot/vmlinuz-* | sort | tail -n1 | sed "s/\(.*\)vmlinuz-//")
if [[ $KERNEL_VER == "" ]]; then
	e_log "   Kernel tidak ditemukan, proses akan dibatalkan :("
	rm -rf "$TEMP_DIR"
	exit 1
fi
KERNEL_SIZE=$(du $IGN_DIR/boot/vmlinuz-$KERNEL_VER | sed -e "s/\t\(.*\)//")
s_log "   Kernel ditemukan: Linux $KERNEL_VER, $KERNEL_SIZE KiB"

### Create ramdisk
s_log "   Membuat initial ramdisk..."
s_mount_cont
s_chroot_cont dracut -f -N --kver="$KERNEL_VER" --add="dmsquash-live" /initrd0.img-buat-livecd > /dev/null
INITRD_SIZE=$(du "$TEMP_DIR/container/initrd0.img-buat-livecd" | sed -e "s/\t\(.*\)//")
s_log "   Initial ramdisk dibuat: $INITRD_SIZE KiB"

### Copy kernel and ramdisk
s_log "   Menyalin kernel..."
cp -f "$IGN_DIR/boot/vmlinuz-$KERNEL_VER" "$TEMP_DIR/temp_iso/isolinux/vmlinuz0"
s_log "   Memindahkan initial ramdisk..."
mv -f "$TEMP_DIR/container/initrd0.img-buat-livecd" "$TEMP_DIR/temp_iso/isolinux/initrd0.img"
s_umount_cont

## Compress rootfs.img using SquasfFS
s_log "-> Mengompres LiveOS..."
s_log "   (mungkin lama, tergantung kemampuan CPU dan ukuran LiveOS)"
pushd "$TEMP_DIR/" > /dev/null
mksquashfs LiveOS "$TEMP_DIR/temp_iso/LiveOS/squashfs.img" -comp $SQUASHFS_COMP -keep-as-directory
popd > /dev/null

## Create ISO using xorriso
s_log "-> Membuat ISO..."
pushd "$TEMP_DIR/temp_iso/" > /dev/null
if [ -f "$ISO_CONF/isohdpfx.bin" ]; then
	s_log "   Hybrid ISO"
	XORRISO_PARAM="-isohybrid-mbr $ISO_CONF/isohdpfx.bin"
else
	s_log "   Non-hybrid ISO"
fi
	xorriso -as mkisofs -o $WORKING_DIR/IGNX-Remastered_$DATE.iso -V "IGNX" -input-charset utf8 -J -R $XORRISO_PARAM -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table .
popd > /dev/null
chmod 666 "$WORKING_DIR/IGNX-Remastered_$DATE.iso"
sync

# Generate MD5 checksum
if [[ "$GENERATE_MD5" == "1" ]]; then
	s_log "-> Membuat MD5 sum..."
	pushd "$WORKING_DIR" > /dev/null
	md5sum IGNX-Remastered_$DATE.iso > IGNX-Remastered_$DATE.iso.md5
	chmod 666 IGNX-Remastered_$DATE.iso.md5
	popd > /dev/null
fi

s_log ""
s_log "Bersih-bersih..."
s_umount_iso
rm -rf "$TEMP_DIR"
s_log "Selesai!"
